import { FormEvent, useEffect, useMemo, useState } from 'react';
import { dateDiff, daysBetween, fmtLong, fmtShort, fromISO, localISO, nextOccurrence, previousOccurrence, recurrenceLabel } from './dateUtils';
import type { Recurrence, SavedEvent } from './types';

const STORE='how-many-days-events', THEME='how-many-days-theme';
const quick=[['🎆','New Year','01-01'],['🎄','Christmas','12-25'],['💌',"Valentine's Day",'02-14'],['🎃','Halloween','10-31']];
const read=()=>{try{return JSON.parse(localStorage.getItem(STORE)||'[]') as SavedEvent[]}catch{return []}};
function message(days:number){if(days===0)return "🎉 It's today!";if(days===1)return 'Almost there — 1 day to go.';if(days===7)return 'One week to go!';if(days===14)return 'Two weeks to go!';if(days===100)return '✨ Exactly 100 days!';return days<0?`That was ${Math.abs(days)} days ago.`:''}
export default function App(){
 const [events,setEvents]=useState<SavedEvent[]>(read),[date,setDate]=useState(''),[name,setName]=useState(''),[recurrence,setRecurrence]=useState<Recurrence>('none'),[leapRule,setLeapRule]=useState<'feb28'|'mar1'>('feb28'),[result,setResult]=useState<SavedEvent|null>(null),[editing,setEditing]=useState<string|null>(null),[dark,setDark]=useState(false),[birth,setBirth]=useState('');
 useEffect(()=>{const p=localStorage.getItem(THEME);const v=p?p==='dark':matchMedia('(prefers-color-scheme: dark)').matches;setDark(v);document.documentElement.dataset.theme=v?'dark':'light'},[]);
 useEffect(()=>localStorage.setItem(STORE,JSON.stringify(events)),[events]);
 const toggle=()=>{const v=!dark;setDark(v);document.documentElement.dataset.theme=v?'dark':'light';localStorage.setItem(THEME,v?'dark':'light')};
 const save=(e:FormEvent)=>{e.preventDefault();if(!date)return;const item:SavedEvent={id:editing||crypto.randomUUID(),name:name.trim(),emoji:'',date,recurrence,leapRule,createdAt:editing?events.find(x=>x.id===editing)?.createdAt||localISO():localISO()};if(editing)setEvents(es=>es.map(x=>x.id===editing?item:x));else setEvents(es=>[item,...es]);setResult(item);setDate('');setName('');setRecurrence('none');setEditing(null)};
 const calculate=(e:SavedEvent)=>{setResult(e);window.scrollTo({top:0,behavior:'smooth'})};
 const startEdit=(e:SavedEvent)=>{setEditing(e.id);setDate(e.date);setName(e.name);setRecurrence(e.recurrence);setLeapRule(e.leapRule);document.getElementById('count-form')?.scrollIntoView({behavior:'smooth'})};
 const today=new Date(); const target=result?nextOccurrence(result):null; const delta=target?daysBetween(today,target):0;
 const age=useMemo(()=>birth?dateDiff(fromISO(birth),today):null,[birth]);
 const addQuick=(emoji:string,n:string,md:string)=>{let y=today.getFullYear();let d=new Date(`${y}-${md}T00:00:00`);if(daysBetween(today,d)<0)y++;setDate(`${y}-${md}`);setName(n);setRecurrence('yearly');setTimeout(()=>document.getElementById('count-form')?.scrollIntoView({behavior:'smooth'}),0)};
 const share=(e:SavedEvent)=>{const t=nextOccurrence(e), n=daysBetween(today,t), title=e.name||fmtShort(t), text=n===0?`🎉 ${title} is today!`:`${e.emoji||'📅'} ${title} is in ${n} ${n===1?'day':'days'}.`;if(navigator.share)navigator.share({title:'How Many Days?',text}).catch(()=>{});else navigator.clipboard.writeText(text)};
 return <main><header><a className="brand" href="#top">how many days<span>?</span></a><button className="icon" onClick={toggle} aria-label="Toggle dark mode">{dark?'☀︎':'☾'}</button></header>
 <section className="hero" id="top"><p className="eyebrow">A tiny date utility</p><h1>How many days<span>?</span></h1><p className="lede">Pick a date. We’ll do the counting.</p>
 <form id="count-form" onSubmit={save} className="count-form"><label><span>Date</span><input type="date" value={date} onChange={e=>setDate(e.target.value)} required /></label><label><span>What are you counting down to? <i>optional</i></span><input value={name} onChange={e=>setName(e.target.value)} placeholder="My birthday, a trip…" maxLength={60}/></label><div className="form-row"><label><span>Repeats</span><select value={recurrence} onChange={e=>setRecurrence(e.target.value as Recurrence)}><option value="none">Doesn’t repeat</option><option value="yearly">Every year</option><option value="monthly">Every month</option></select></label>{recurrence==='yearly'&&date.endsWith('-02-29')&&<label><span>In non-leap years</span><select value={leapRule} onChange={e=>setLeapRule(e.target.value as 'feb28'|'mar1')}><option value="feb28">February 28</option><option value="mar1">March 1</option></select></label>}</div><button className="primary" type="submit">{editing?'Save changes':'Count days'} <b>→</b></button>{editing&&<button type="button" className="cancel" onClick={()=>{setEditing(null);setDate('');setName('')}}>Cancel</button>}</form>
 </section>
 {result&&target&&<section className="result" aria-live="polite"><div className="result-card"><p className="eyebrow">{delta===0?'Right now':delta>0?'Your countdown':'Looking back'}</p><div className="number">{delta===0?'Today':Math.abs(delta)}</div><h2>{delta===0?'🎉 It’s today!':<>{delta>0?'days until':'days since'} <em>{result.name||fmtLong(target)}</em></>}</h2><p className="date-line">{fmtLong(target)}</p>{message(delta)&&<p className="delight">{message(delta)}</p>}<div className="result-actions"><button onClick={()=>share(result)}>Share</button><button onClick={()=>navigator.clipboard.writeText(delta===0?`${result.name||'My event'} is today!`:`${result.name||'My event'} is ${Math.abs(delta)} days ${delta>0?'away':'ago'}.`)}>Copy</button></div></div><aside className="about"><p className="eyebrow">About this date</p><strong>{Math.abs(delta)} {Math.abs(delta)===1?'day':'days'}</strong><span>{delta>=0?'until the event':'since the event'}</span><hr/><strong>{Math.floor(Math.abs(delta)/7)} weeks + {Math.abs(delta)%7} days</strong><span>in weeks</span></aside></section>}
 <section className="quick"><p className="eyebrow">Quick add</p><div>{quick.map(([e,n,d])=><button key={n} onClick={()=>addQuick(e,n,d)}><b>{e}</b>{n}</button>)}<button onClick={()=>document.getElementById('count-form')?.scrollIntoView({behavior:'smooth'})}><b>＋</b>Custom date</button></div></section>
 <section className="events"><div className="section-head"><div><p className="eyebrow">Your saved dates</p><h2>My events</h2></div><span>{events.length} {events.length===1?'event':'events'}</span></div>{events.length===0?<div className="empty">Your saved countdowns will appear here.<br/><button onClick={()=>document.getElementById('count-form')?.scrollIntoView({behavior:'smooth'})}>Add your first event →</button></div>:<div className="grid">{events.map(e=><EventCard key={e.id} event={e} onCount={calculate} onEdit={startEdit} onDelete={()=>setEvents(es=>es.filter(x=>x.id!==e.id))} onShare={share}/>)}</div>}</section>
 <section className="age"><div><p className="eyebrow">A little extra</p><h2>How long have I lived?</h2><p>Enter your date of birth for a calendar-accurate age.</p></div><div><label>Date of birth<input type="date" max={localISO()} value={birth} onChange={e=>setBirth(e.target.value)}/></label>{age&&<p className="age-result">You are <b>{age.y} years, {age.m} months, and {age.d} days</b> old.<small>Approximately {Math.max(0,daysBetween(fromISO(birth),today)).toLocaleString()} days old.</small></p>}</div></section>
 <footer><span>🔒 Your events stay on this device. Nothing is uploaded.</span><button onClick={()=>{if(confirm('Clear every saved event and theme preference?')){localStorage.removeItem(STORE);setEvents([])}}}>Clear all data</button></footer></main>
}
function EventCard({event,onCount,onEdit,onDelete,onShare}:{event:SavedEvent;onCount:(e:SavedEvent)=>void;onEdit:(e:SavedEvent)=>void;onDelete:()=>void;onShare:(e:SavedEvent)=>void}){const today=new Date(), target=nextOccurrence(event),days=daysBetween(today,target),prev=previousOccurrence(event,target);let progress:number|null=null;if(prev){const total=daysBetween(prev,target);progress=total?Math.min(100,Math.max(0,daysBetween(prev,today)/total*100)):null}else{const made=fromISO(event.createdAt),total=daysBetween(made,target);if(total>0&&days>=0)progress=Math.min(100,Math.max(0,daysBetween(made,today)/total*100));}return <article className="event-card"><div className="card-top"><span className="event-dot">{event.emoji||'✦'}</span><div><h3>{event.name||'Untitled date'}</h3><p>{recurrenceLabel(event.recurrence)}</p></div><button className="menu" aria-label={`Edit ${event.name||'event'}`} onClick={()=>onEdit(event)}>•••</button></div><button className="card-count" onClick={()=>onCount(event)}><strong>{days===0?'Today':Math.abs(days)}</strong><span>{days===0?'it’s here':`${days<0?'since':'until'} ${fmtShort(target)}`}</span></button>{progress!==null&&<div className="progress" aria-label={`${Math.round(progress)} percent complete`}><i style={{width:`${progress}%`}}/></div>}<div className="card-actions"><button onClick={()=>onShare(event)}>Share</button><button onClick={()=>onEdit(event)}>Edit</button><button className="danger" onClick={()=>{if(confirm(`Delete ${event.name||'this event'}?`))onDelete()}}>Delete</button></div></article>}
